sources:
  - name: cyrusofeden/cap
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/cyrusofeden/cap
        timeout: 30000
        retry: 3
        batch: true
    transforms:
      - autoPagination:
          validateSchema: true
